from __future__ import annotations

from typing import Any, Awaitable, Callable

class Isolates:
    """A frozen singleton for V8 Isolates.

    That is:
    ```python
    isolates0 = Isolates()
    isolates1 = Isolates()
    assert isolates0 is isolates1
    ```

    To create an isolates, see the asynchronous method `Isolates.create_isolate()`.
    """

    def __init__(self) -> None: ...
    async def create_isolate(
        self, funcs: dict[str, Callable[..., Any]] | None = None
    ) -> Isolate: ...

class Isolate:
    def add_function(self, name: str, f: Callable[..., Awaitable[Any]]): ...
    async def run(self, source: str) -> Any: ...

class Value:
    """Represents a v8 value.

    Upon conversion, the value itself gets released,
    meaning you can only do conversion once.
    """
    def to_null(self) -> None: ...
    def to_undefined(self) -> undefined: ...
    def to_str(self) -> str: ...
    def to_bool(self) -> bool: ...
    def to_bigint(self) -> int: ...
    def to_float(self) -> float: ...
    def to_uint(self) -> int: ...
    def to_int(self) -> int: ...
    def release(self) -> None: ...

class undefined: ...
